import { PART } from "..";
import { TransType, Trans } from "./common";

export const PartDict: TransType<PART> = {
  ko: {
    TOP: "상의",
    BOTTOM: "하의",
    OUTER: "외투",
    DRESS: "드레스",
    SHOES: "신발",
    BAG: "가방",
    HAT: "모자",
    ETC: "기타",
  },
  en: {
    TOP: "Top",
    BOTTOM: "Bottom",
    OUTER: "Outer",
    DRESS: "Dress",
    SHOES: "Shoes",
    BAG: "Bag",
    HAT: "Hat",
    ETC: "Etc",
  },
  cn: {
    TOP: "상의",
    BOTTOM: "하의",
    OUTER: "외투",
    DRESS: "드레스",
    SHOES: "신발",
    BAG: "가방",
    HAT: "모자",
    ETC: "기타",
  },
};

export const CtgrDict: Trans = {
  ko: {
    T_SHIRT: "티셔츠",
    BLOUSE: "블라우스",
    HOODIE: "후드",
    SHIRT: "셔츠",
    SLEEVELESS: "나시",
    KNIT: "니트",
    SWEATER: "스웨터",
    SWEAT_SHIRT: "스웻셔츠",
    CARDIGAN: "가디건",
    KNIT_CARDIGAN: "니트가디건",
    KNIT_T_SHIRT: "니트티셔츠",
    ETC: "기타",
    JEAN: "청바지",
    LEGGINGS: "레깅스",
    PANTS: "팬츠",
    SHORTS: "쇼츠",
    SKIRTS: "스커트",
    SLACKS: "슬랙스",
    TRAINING_PANT: "트레이닝팬츠",
    BLAZER: "블레이저",
    COAT: "코트",
    JACKET: "자켓",
    PUFFER_DOWN: "패딩",
    VEST: "베스트",
    SUIT: "수트",
    DRESS: "드레스",
    ONE_PIECE: "원피스",
    JUMP_SUIT: "점프수트",
    WEDDING_DRESS: "웨딩드레스",
    SLIPPERS: "슬리퍼", // 슬리퍼
    SANDALS: "샌들", // 샌달
    BOOTS: "부츠", // 부츠
    PUMPS: "펌프스", // 고리나 끈, 잠금 장치 등이 없고 발등 부분이 드러나게 깊이 파져 있는 여성용 구두.
    FLATS: "플랫",
    LOAFERS: "로퍼",
    ATHLETIC: "운동화",
    WEDGE_HEEL: "웨지힐",
    HAND_MADE: "수제화",
    BACKPACK: "백팩",
    LEATHER: "가죽",
    CROSS: "크로스",
    CLUTCH: "클러치",
    HANDBAG: "핸드백",
    MINI_BAG: "미니백",
    TOD_BAG: "토트백",
    ECO_BAG: "에코백",
    SHOULDER: "숄더",
    WALLET: "지갑",
    NECKLACE: "목걸이",
    RING: "반지",
    WATCH: "시계",
    SCARP: "스카프",
    BELT: "벨트",
    BAND: "밴드",
    GLASSES: "안경",
    SUN_GLASSES: "선글라스",
    CAP: "캡",
    FEDORA: "패도라",
    BERET: "Beret",
    FLOPPY: "플로피",
    SNAPBACK: "스냅백",
    BEANIE: "비니",
    CLOCHE: "Cloche",
    TRAPPER: "Trapper",
    BUCKET: "버킷",
    BOATER: "Boater",
    TOP_BOTTOM_SET: "상하의세트",
    SUIT_SET: "수트세트",
    BIG_SIZE: "비사이즈",
    MATERNITY: "임부",
  },
  en: {
    T_SHIRT: "T_SHIRT",
    BLOUSE: "BLOUSE",
    HOODIE: "HOODIE",
    SHIRT: "SHIRT",
    SLEEVELESS: "SLEEVELESS",
    KNIT: "KNIT",
    SWEATER: "SWEATER",
    SWEAT_SHIRT: "SWEAT_SHIRT",
    CARDIGAN: "CARDIGAN",
    KNIT_CARDIGAN: "KNIT_CARDIGAN",
    KNIT_T_SHIRT: "KNIT_T_SHIRT",
    ETC: "ETC",
    JEAN: "JEANS",
    LEGGINGS: "LEGGINGS",
    PANTS: "PANTS",
    SHORTS: "SHORTS",
    SKIRTS: "SKIRTS",
    SLACKS: "SLACKS",
    TRAINING_PANT: "TRAINING_PANT",
    BLAZER: "BLAZER",
    COAT: "COAT",
    JACKET: "JACKET",
    PUFFER_DOWN: "PUFFER_DOWN",
    VEST: "VEST",
    SUIT: "SUIT",
    DRESS: "DRESS",
    ONE_PIECE: "ONE_PIECE",
    JUMP_SUIT: "JUMP_SUIT",
    WEDDING_DRESS: "WEDDING_DRESS",
    SLIPPERS: "SLIPPERS", // 슬리퍼
    SANDALS: "SANDALS", // 샌달
    BOOTS: "BOOTS", // 부츠
    PUMPS: "PUMPS", // 고리나 끈, 잠금 장치 등이 없고 발등 부분이 드러나게 깊이 파져 있는 여성용 구두.
    FLATS: "FLATS",
    LOAFERS: "LOAFERS",
    ATHLETIC: "ATHLETIC",
    WEDGE_HEEL: "WEDGE_HEEL",
    HAND_MADE: "HAND_MADE",
    BACKPACK: "BACKPACK",
    LEATHER: "LEATHER",
    CROSS: "CROSS",
    CLUTCH: "CLUTCH",
    HANDBAG: "HANDBAG",
    MINI_BAG: "MINI_BAG",
    TOD_BAG: "TOD_BAG",
    ECO_BAG: "ECO_BAG",
    SHOULDER: "SHOULDER",
    WALLET: "WALLET",
    NECKLACE: "NECKLACE",
    RING: "RING",
    WATCH: "WATCH",
    SCARP: "SCARP",
    BELT: "BELT",
    BAND: "BAND",
    GLASSES: "GLASSES",
    SUN_GLASSES: "SUN_GLASSES",
    CAP: "CAP",
    FEDORA: "FEDORA",
    BERET: "BERET",
    FLOPPY: "FLOPPY",
    SNAPBACK: "SNAPBACK",
    BEANIE: "BEANIE",
    CLOCHE: "CLOCHE",
    TRAPPER: "TRAPPER",
    BUCKET: "BUCKET",
    BOATER: "BOATER",
    TOP_BOTTOM_SET: "TOP_BOTTOM_SET",
    SUIT_SET: "SUIT_SET",
    BIG_SIZE: "BIG_SIZE",
    MATERNITY: "MATERNITY",
  },
  cn: {
    T_SHIRT: "T_SHIRT",
    BLOUSE: "BLOUSE",
    HOODIE: "HOODIE",
    SHIRT: "SHIRT",
    SLEEVELESS: "SLEEVELESS",
    KNIT: "KNIT",
    SWEATER: "SWEATER",
    SWEAT_SHIRT: "SWEAT_SHIRT",
    CARDIGAN: "CARDIGAN",
    KNIT_CARDIGAN: "KNIT_CARDIGAN",
    KNIT_T_SHIRT: "KNIT_T_SHIRT",
    ETC: "ETC",
    JEAN: "JEANS",
    LEGGINGS: "LEGGINGS",
    PANTS: "PANTS",
    SHORTS: "SHORTS",
    SKIRTS: "SKIRTS",
    SLACKS: "SLACKS",
    TRAINING_PANT: "TRAINING_PANT",
    BLAZER: "BLAZER",
    COAT: "COAT",
    JACKET: "JACKET",
    PUFFER_DOWN: "PUFFER_DOWN",
    VEST: "VEST",
    SUIT: "SUIT",
    DRESS: "DRESS",
    ONE_PIECE: "ONE_PIECE",
    JUMP_SUIT: "JUMP_SUIT",
    WEDDING_DRESS: "WEDDING_DRESS",
    SLIPPERS: "SLIPPERS", // 슬리퍼
    SANDALS: "SANDALS", // 샌달
    BOOTS: "BOOTS", // 부츠
    PUMPS: "PUMPS", // 고리나 끈, 잠금 장치 등이 없고 발등 부분이 드러나게 깊이 파져 있는 여성용 구두.
    FLATS: "FLATS",
    LOAFERS: "LOAFERS",
    ATHLETIC: "ATHLETIC",
    WEDGE_HEEL: "WEDGE_HEEL",
    HAND_MADE: "HAND_MADE",
    BACKPACK: "BACKPACK",
    LEATHER: "LEATHER",
    CROSS: "CROSS",
    CLUTCH: "CLUTCH",
    HANDBAG: "HANDBAG",
    MINI_BAG: "MINI_BAG",
    TOD_BAG: "TOD_BAG",
    ECO_BAG: "ECO_BAG",
    SHOULDER: "SHOULDER",
    WALLET: "WALLET",
    NECKLACE: "NECKLACE",
    RING: "RING",
    WATCH: "WATCH",
    SCARP: "SCARP",
    BELT: "BELT",
    BAND: "BAND",
    GLASSES: "GLASSES",
    SUN_GLASSES: "SUN_GLASSES",
    CAP: "CAP",
    FEDORA: "FEDORA",
    BERET: "BERET",
    FLOPPY: "FLOPPY",
    SNAPBACK: "SNAPBACK",
    BEANIE: "BEANIE",
    CLOCHE: "CLOCHE",
    TRAPPER: "TRAPPER",
    BUCKET: "BUCKET",
    BOATER: "BOATER",
    TOP_BOTTOM_SET: "TOP_BOTTOM_SET",
    SUIT_SET: "SUIT_SET",
    BIG_SIZE: "BIG_SIZE",
    MATERNITY: "MATERNITY",
  },
};
